[workspace]

members = [
    "ndarray",
    "metrics",
    "autodiff",
    "regression",
    "preprocessing",
    "models",
    "datasets",
    "trees",
    "bayes", 
    "knn"
]


[workspace.package]
name = "steepgrad"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
ndarray = { path= "./ndarray" }
metrics = { version = "0.3.0", path= "./metrics" }
autodiff = { version = "0.3.0", path= "./autodiff" }
regression = { version = "0.3.0", path= "./regression" }
preprocessing = { version = "0.3.0", path= "./preprocessing" }
models = { version = "0.3.0", path= "./models" }
datasets = { version = "0.3.0", path= "./datasets" }
trees = { version = "0.3.0", path= "./trees" }
bayes = { version = "0.3.0", path= "./bayes" }
knn = { version = "0.3.0", path= "./knn" }
