[workspace]

members = [
    "ndarray",
    "metrics",
    "autodiff",
    "regression",
    "preprocessing",
    "models"
]


[workspace.package]
name = "steepgrad"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
ndarray = { path= "./ndarray" }
metrics = { version = "0.3.0", path= "./metrics" }
autodiff = { version = "0.3.0", path= "./autodiff" }
regression = { version = "0.3.0", path= "./regression" }
preprocessing = { version = "0.3.0", path= "./preprocessing" }
models = { version = "0.3.0", path= "./models" }

#rand = "0.8"
#serde = { version = "1.0.126", features = ["derive"] }
#serde_json = "1.0.64"
#arrow = "51.0.0"
#arrow-schema = "51.0.0"
#arrow-array = "51.0.0"
#postgres = "0.19.7"
#parquet = "52.0.0"
#bigdecimal = "0.4.4"
#csv = "1.3.0"
