name: Dendritic

on:
  pull_request:
    branches: [ "master" ]

jobs:

  ndarray:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Build
      working-directory: "./dendritic-ndarray"
      run: cargo build --color always

    - name: Test
      working-directory: "./dendritic-ndarray"
      run: cargo test --release --color always

  metrics:
    runs-on: ubuntu-20.04
    needs: [ndarray]
    steps:
    - uses: actions/checkout@v2

    - name: Build
      working-directory: "./dendritic-metrics"
      run: cargo build --color always

    - name: Test
      working-directory: "./dendritic-metrics"
      run: cargo test --release --color always

  autodiff:
    runs-on: ubuntu-20.04
    needs: [ndarray]
    steps:
    - uses: actions/checkout@v2

    - name: Build
      working-directory: "./dendritic-autodiff"
      run: cargo build --color always

    - name: Test
      working-directory: "./dendritic-autodiff"
      run: cargo test --release --color always

  preprocessing:
    runs-on: ubuntu-20.04
    needs: [ndarray]
    steps:
    - uses: actions/checkout@v2

    - name: Build
      working-directory: "./dendritic-preprocessing"
      run: cargo build --color always

    - name: Test
      working-directory: "./dendritic-preprocessing"
      run: cargo test --release --color always

  datasets:
    runs-on: ubuntu-20.04
    needs: [ndarray]
    steps:
    - uses: actions/checkout@v2

    - name: Build
      working-directory: "./dendritic-datasets"
      run: cargo build --color always

    - name: Test
      working-directory: "./dendritic-datasets"
      run: cargo test --release --color always

  trees:
    runs-on: ubuntu-20.04
    needs: [ndarray, metrics, autodiff, preprocessing, datasets]
    steps:
    - uses: actions/checkout@v2

    - name: Build
      working-directory: "./dendritic-trees"
      run: cargo build --color always

    - name: Test
      working-directory: "./dendritic-trees"
      run: cargo test --release --color always

  knn:
    runs-on: ubuntu-20.04
    needs: [ndarray, metrics, autodiff, preprocessing, datasets]
    steps:
    - uses: actions/checkout@v2

    - name: Build
      working-directory: "./dendritic-knn"
      run: cargo build --color always

    - name: Test
      working-directory: "./dendritic-knn"
      run: cargo test --release --color always


  regression:
    runs-on: ubuntu-20.04
    needs: [ndarray, metrics, autodiff, preprocessing, datasets]
    steps:
    - uses: actions/checkout@v2

    - name: Build
      working-directory: "./dendritic-regression"
      run: cargo build --color always

    - name: Test
      working-directory: "./dendritic-regression"
      run: cargo test --release --color always

  bayes:
    runs-on: ubuntu-20.04
    needs: [ndarray, metrics, autodiff, preprocessing, datasets]
    steps:
    - uses: actions/checkout@v2

    - name: Build
      working-directory: "./dendritic-bayes"
      run: cargo build --color always

    - name: Test
      working-directory: "./dendritic-bayes"
      run: cargo test --release --color always

  clustering:
    runs-on: ubuntu-20.04
    needs: [ndarray, metrics, autodiff, preprocessing, datasets]
    steps:
    - uses: actions/checkout@v2

    - name: Build
      working-directory: "./dendritic-clustering"
      run: cargo build --color always

    - name: Test
      working-directory: "./dendritic-clustering"
      run: cargo test --release --color always


