name: Publish to Crates.io

on:
  release:
    types:
      - created

jobs:

  publish-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Publish NDArray Package
        run: cargo publish --token $CRATES_IO_TOKEN
        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATE_TOKEN }}


  publish-ndarray:
    needs: [publish-project]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Publish NDArray Package
        run: cargo publish --token $CRATES_IO_TOKEN
        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATE_TOKEN }}
        working-directory: crates/dendritic-ndarray

  publish-metrics:
    needs: [publish-project]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Publish Metrics Package
        run: cargo publish --token $CRATES_IO_TOKEN
        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATE_TOKEN }}
        working-directory: crates/dendritic-metrics


  publish-preprocessing:
    needs: [publish-project]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Publish Preprocessing Package
        run: cargo publish --token $CRATES_IO_TOKEN
        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATE_TOKEN }}
        working-directory: crates/dendritic-preprocessing


  publish-datasets:
    needs: [publish-project]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Publish Datasets Package
        run: cargo publish --token $CRATES_IO_TOKEN
        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATE_TOKEN }}
        working-directory: crates/dendritic-datasets


  publish-autodiff:
    needs: [publish-project]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Publish Autodiff Package
        run: cargo publish --token $CRATES_IO_TOKEN
        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATE_TOKEN }}
        working-directory: crates/dendritic-autodiff




  publish-bayes:
    needs: [publish-project]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Publish Bayes Package
        run: cargo publish --token $CRATES_IO_TOKEN
        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATE_TOKEN }}
        working-directory: crates/dendritic-bayes


  publish-clustering:
    needs: [publish-project]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Publish Clustering Package
        run: cargo publish --token $CRATES_IO_TOKEN
        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATE_TOKEN }}
        working-directory: crates/dendritic-clustering


  publish-regression:
    needs: [publish-project]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
i
      - name: Publish Regression Package
        run: cargo publish --token $CRATES_IO_TOKEN
        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATE_TOKEN }}
        working-directory: crates/dendritic-regression


  publish-trees:
    needs: [publish-project]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
i
      - name: Publish Trees Package
        run: cargo publish --token $CRATES_IO_TOKEN
        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATE_TOKEN }}
        working-directory: crates/dendritic-trees

  publish-models:
    needs: [publish-project]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Publish Models Package
        run: cargo publish --token $CRATES_IO_TOKEN
        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATE_TOKEN }}
        working-directory: crates/dendritic-models